MRP_price = input("Enter the MRP price: ")
print("="*30)
x = float(MRP_price)
print("product MRP price:", MRP_price,"RS")
print("="*30)
Discount = input("Enter the discount percentage: ")
print("="*30)
y = int(Discount)
print("discount percentage:", Discount, "%")
print("="*30)
Dis = y/100
selling_price = x - (x * Dis)
print("selling price of the product:", selling_price,"RS")
print("="*30)